.PHONY: all single_page_backend temperature timer flight circles spreadsheet reference file_select

all: single_page_backend temperature timer flight circles spreadsheet reference file_select


single_page_backend:
	dune build ./single_page_backend.exe


temperature:
	dune build ./temperature.js


timer:
	dune build ./timer.js


flight:
	dune build ./flight.js


circles:
	dune build ./circles.js

reference:
	dune build ./reference.js

spreadsheet:
	dune build ./spreadsheet.js

file_select:
	dune build ./file_select.js
