.PHONY: all temperature timer flight circles

all: temperature timer flight circles


temperature:
	dune build ./temperature.js


timer:
	dune build ./timer.js


flight:
	dune build ./flight.js


circles:
	dune build ./circles.js
