.PHONY: all temperature timer flight circles

all: webapp temperature timer flight circles spreadsheet reference file_select


webapp:
	dune build ./webapp.js


temperature:
	dune build ./temperature.js


timer:
	dune build ./timer.js


flight:
	dune build ./flight.js


circles:
	dune build ./circles.js

reference:
	dune build ./reference.js

spreadsheet:
	dune build ./spreadsheet.js

file_select:
	dune build ./file_select.js
